class ArticlesController < ApplicationController
  
  def new
    @article = Article.new
  end
  
  def create
    #render plain: params[:article].inspect ***Allows me to see in the browser the params generated by the form***
    @article = Article.new(article_params)
    if @article.save
      #***Do this when the validations are OK***
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      #***Do this when did not pass the validations***
      render 'new'
    end

  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end
  
end